FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:2.12.1-cpu

ADD requirements-inference.txt /opt/requirements.txt
RUN pip3 install -r /opt/requirements.txt

ADD ./inference.py /opt/inference.py
ADD ./abalone_model.keras /model/abalone_model.keras
ADD ./test.sh /opt/test.sh

ENV FLASK_APP=/opt/inference.py

# Entrypoint to handle SageMaker's serve argument
ENTRYPOINT ["/opt/test.sh"]